export const projects = [
  {
    title: ' Food Kh',
    description: " This site is designed to get all kinds of foods, recipes and special ingredients for each type of food, and there is a classification by country or continent by spoonacular API",
    image: '/images/Food-app.png',
    tags: ['React', 'jsx', '@fremer-motion', '@splidejs/react-splide', '@react-icon'],
    source: 'https://github.com/ahmadkhatib1/Food-app',
    visit: 'https://food-ahk.netlify.app',
    id: 5,
    type: 1,
  },
  {
    title: 'Dashboard',
    description: " The control is designed by a set of special tools by syncfusion It includes customers, employees, a set of programs such as a calendar, a caban for organizing tasks, and a colorPiker for choosing colorsA set of cool charts with dummy data to simulateYou can also choose the night mode and choose the appropriate times",
    image: '/images/8.png',
    tags: ['React', 'jsx', 'tawillnd', '@syncfusion', '@react-icon'],
    source: 'https://github.com/ahmadkhatib1/Best-Dashbord',
    visit: 'https://dashbord-ahmadkhatib1.vercel.app/',
    id: 8,
    type: 1,
  },
  {
    title: 'Protofileo',
    description: "This site is built to simulate a gallery of works with some animation, day mode and dark mode",
    image: '/images/9.png',
    tags: ['React', 'styled-components', '@fremer-motion', '@emailj', 'react-i18next', 'swiper'],
    source: 'https://github.com/ahmadkhatib1/protofileo2',
    visit: 'https://protofileo2.vercel.app/',
    id: 9,
    type: 1,
  },
  {
    title: ' Google-Clone',
    description: " This application works as a Google search engine. The api is taken from rapid.api It searches for photos, news and videos",
    image: '/images/7.png',
    tags: ['React', 'jsx', 'tailwindcss', '@react-icon'],
    source: 'https://github.com/ahmadkhatib1/GoogleSearch-clone',
    visit: 'https://google-search-clone-ahmadkhatib1.vercel.app/search',
    id: 7,
    type: 1,
  },

  {
    title: ' pizza order',
    description: " The application is a pizza ordering program that focused on building the application on animation through the fremermotion library",
    image: '/images/6.png',
    tags: ['React', 'jsx', '@fremer-motion'],
    source: 'https://github.com/ahmadkhatib1/pizza-joint',
    visit: 'https://pizaa-kh.netlify.app/',
    id: 6,
    type: 1,
  },

  {
    title: ' Keeper clone',
    description: "A personal website designed to display your information, projects, and services. Designed by html & css. The site is responsive to all screens.",
    image: '/images/Keeper.png',
    tags: ['React', 'jsx', 'matrial/ui'],
    source: 'https://github.com/ahmadkhatib1/KeeperClone',
    visit: 'https://keeperclon.netlify.app/',
    id: 1,
    type: 1,
  },

  {
    title: 'Lion Design',
    description: " A personal website designed to display your information, projects and services. Designed by html & css",
    image: '/images/3.png',
    tags: ['Html', 'Css'],
    source: 'https://github.com/ahmadkhatib1/LionDesign',
    visit: 'https://ahmadkhatib1.github.io/LionDesign/',
    id: 2,
    type: 2,
  },
  {
    title: 'Kasperr Desin',
    description: "A personal website designed to display your information, projects, and services. Designed by html & css. The site is responsive to all screens.",
    image: '/images/2.png',
    tags: ['Html', 'Css'],
    source: 'https://github.com/ahmadkhatib1/Kasper-Design',
    visit: 'https://ahmadkhatib1.github.io/Kasper-Design/',
    id: 3,
    type: 2,
  },
  {
    title: 'Todo List',
    description: "Through this application, you can organize your day and arrange all your daily necessities This application was built by React.js and also saves data through the browser's local storage",
    image: '/images/1.png',
    tags: ['jsx', 'React', 'css'],
    source: 'https://github.com/ahmadkhatib1/Todo-List',
    visit: 'https://todo-list-dev-khatib.netlify.app/',
    id: 0,
    type: 1,
  },
  {
    title: 'MENTUM',
    description: "A personal website designed to display your information, projects, and services. Designed by html & css. The site is responsive to all screens.",
    image: '/images/4.png',
    tags: ['Html', 'Css'],
    source: 'https://ahmadkhatib1.github.io/MENTUM-TEMPLATE/',
    visit: 'https://github.com/ahmadkhatib1/MENTUM-TEMPLATE',
    id: 4,
    type: 2,
  },
];

export const TimeLineData = [
  {
    year: 2016, text: 'Entry to the university Engineering is a specialization in information technology',
  },
  { year: 2018, text: 'Learn to c++', },
  { year: 2019, text: 'Learn to c# & sql,OracleDb apply several projects', },
  { year: 2020, text: 'Learn to Html Css js and some knowledge asp.net mvc apply several projects  ', },
  { year: 2021, text: 'Learn to React js and some in larvel &my sql  ,  graduated from the University of,Working on a group of projects Worked as a freelance developer ', },
];